# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Data-ssung
tagline:             '데이터 분석가'
description:         'To be Data scientist'
url:                 https://sung-mi.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sung Mi
  url:               https://sung-mi.github.io
  email:             s@ss.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

github:
  repo: 'https://github.com/sung-mi/sung-mi.github.io'

category_dir: category/
tag_dir: tag/

excerpt_separator: ""
